### ISSUE TITLE
Limits on open files.

### ISSUE THREAD

**Issue by drydenp** [torarnv/sparsebundlefs#20]
Perhaps it would be welcome to suggest that on larger (TimeMachine) backups you need to be able to have more files open for the user sparsebundlefs is running under.

And indeed for the root user the default is 1023 open files. Sparsebundlefs will apparently open as many files as there are bundles. Even a ~ 62GB backup may have more than 2000 (hex) bundles.

Those are user filelimits (even for root) and require setting a line in /etc/security/limits.conf.

A line like: root    hard    nofile  128000

I don't even know what hard and soft limits are, but setting them to 128000 and 64000 respectively alleviated my problems.

Regards.

**Comment by reinhard-brandstaedter** [comment]
I ran into the same issue while restoring from a 2Tb sparsebundle file. Only found out after I switched to run in foreground and sparsebundle was complaining about open files.
The copy process I did was stuck with error messages about the loopback device in syslog.

I eventually had to switch to 1000000 (yes that's 10^6 !) open files!

**Comment by drydenp** [comment]
Agree with that, my mount kept disappearing and I didn't know why until I ran it in the foreground with debug. Seems silly that it keeps all files open. Because of these issues I now turned the sparse backup into a real sparse file on the local fs so I won't have to deal with it anymore ;-). Which has its own issues (not easy to send over a pipe or network link unless you archive it) and then I had the next issue that tar -S refuses to do anything on the file :S. Just doesn't work, I had to use "dar" which is its own anomaly but at least it automatically stores sequences of zeroes as "sparse entries". So for archival purposes I now simply have an "automatically compacted" dar file. Or files. Not knowing why sparsebundlefs crashed made it a really time consuming thing.

**Comment by drydenp** [comment]
Dar automatically uses seeks when extracting a file that has holes in it so after all the actual data is extracted it will just instantly seek to the end and create that huge sparse file. Dar has the drawback of spending a lot of time on a single core after creating the archive to create some catalogue at the end of the archive, which can simply take a long time. It also has a very peculiar syntax very different from tar. Rather hard to use or get to know.

**Comment by torarnv** [comment]
Yes, would be nice to limit the number of open files. I don't have any cycles to look into that right now though, but I'll add it to the list.

**Comment by cluck** [comment]
Some time ago I hacked in write-support and I vaguely remember to have added a LRU list for open files too. But I never finished the whole thing. Feel free to look at https://github.com/cluck/sparsebundlefs/blob/write-support/sparsebundlefs.cpp and cherry-pick what you need. Also check the bits in the various branches.

**Comment by justindressel** [comment]
A bump to this issue:
I just had to restore a time machine backup from a disk that had been logging since 2010. I set my ulimits and security/limits.conf and sysctrl limits as high as possible (999999), and verified those limits were being satisfied by the processes for sparsebundlefs etc, but I still ran out of open files.

To get around this, I manually falsified the #if check on the fuse version to disable the zero copy functionality (and thus disable the map of all open files). This solves the problem so I could restore all the data (THANK YOU!), but did dramatically slow down the file access.

**Comment by wwwenca** [comment]
Hi, I have just made a pull request on this topic.

**Comment by torarnv** [comment]
I've pushed a bunch of fixes and tests related to this that should harden how sparsebundlefs handles open files. 

The reason for keeping files open is that when using the read_buf zero-copy (splice) code path, we're just passing file descriptors back to fuse, so we can't close the file directly after reading it like we do for the non-read_buf mode. I've changed that logic to no longer compute the max number of open files (which was fragile), but instead rely on EMFILE, which should always ensure we close files when needed.

As the logic has now been hardened, the non-read_buf mode has been modified to also keep files open (for improved performance). Passing `-o always_close` overrides this behavior, in case it turns out to be flawed.

There's also a new `-o noreadbu` option to run without the zero-copy code path, for debugging purposes.

Please let me know if you find any more issues related to this, by opening new issues with logs from a recent build of sparsebundlefs, thanks!
