### ISSUE TITLE
bundle has band size 0 and total size 0

### ISSUE THREAD

**Issue by sevn** [torarnv/sparsebundlefs#27]
Trying to recover data off a recovered apple drive and I am currently getting this error message.

```
sparsebundlefs: mounting `/home/storage/apple-drive/Users/.johnsmith/johnsmith.sparsebundle' at mount-point `/tmp/sparse-mnt'
sparsebundlefs: mounting as uid=0, with allow_other=0 and allow_root=0
sparsebundlefs: bundle has band size 0 and total size 0

```

**Comment by torarnv** [comment]
Can you attach the Info.plist inside the sparsebundle?

**Comment by sevn** [comment]
I havn't been able to reproduce this problem since I first opened the issue. I've only come back from holidays and when I've opened a sparsebundle it didn't seem to have an issue. Hopefully nobody else has this issue!

**Comment by eruvaer** [comment]
I also just stumbled into this same issue; the problem was that my default user with which I executed sparsebundlefs did not have permissions to open the sparsebundle. While sparsebundlefs did not throw an error message, the resulting .dmg file had zero size. Running sparsebundlefs from the right user account it now works just fine!
