### ISSUE TITLE
Support for sparseimages (not just sparsebundles)

### ISSUE THREAD

**Issue by aurajamming** [torarnv/sparsebundlefs#7]
When I attempt to load my sparseimage backup of my old macbook, sparsebundlefs doesn't seem to recognize it as containing anything:

```
root@cola-debian:/home/jim/software/sparsebundlefs# ./sparsebundlefs /media/mediadrive/public/MBP\ image.sparseimage /mnt -s -f -D
sparsebundlefs: initialized /media/mediadrive/public/MBP\ image.sparseimage, band size 0, total size 0
```

The sparseimage file is 157 GB - not empty :) It mounts fine in OS X 10.7.

What can I do to determine the error?

**Comment by norpol** [comment]
Since this is still open, and people might still have trouble accessing their data, I'm dropping this workaround here.
---
I ended up using [OSX-KVM](https://github.com/kholia/OSX-KVM).
Best performance I could get was by:
- Setting up a http server (`python3 -m http.server` won't work, due lack of a http-feature, required by `hdiutil`, I chose `lighttpd`, because it has little dependencies)

- Attaching the image inside the OSX vm
`$ hdiutil attach http://host.invalid/image.sparseimage`

- Copying from the OSX vm to my storage using:

Speed | Method
--- | ---
30 MB/s | HTTP attach + smb server running on osx + piping on linux from smb to > /dev/null
15 MB/s | HTTP attach + rsync to nfs share
02 MB/s | sshfs attach + rsync to sshfs

smb-way doesn't keep the permissions, but the modification dates should be preserved. For some reason, using NFS+rsync doesn't preserve the directory dates, file date are preserved . I guess I'm doing something wrong with my NFS setup.

You can mount the OSX SMB share on Linux via.  (requires `cifs-utils` package on Debian). Especially useful if you only need to access certain files quickly.
`sudo mount.cifs //osx-kvm/share /mnt/share -o user=admin,pass=`

If you are completely lost, try pinging me.

**Comment by torarnv** [comment]
Thanks for the workaround @norpol!

**Comment by torarnv** [comment]
Added logic in 5df6fce to error out early if we detect that a sparseimage is opened. Sparse images are an entirely different format, so handling them in this project is unfortunately out of scope. Sorry 😢
